### ISSUE TITLE
How can I compile it? VB give an error...

### ISSUE THREAD

**Issue by ashrambo** [TheRobsCode/TapoMobileApp#1]

**Comment by TheRobsCode** [comment]
I compile it in Visual Studio 2019 or 2022. Make sure you have Xamarin and C# installed.

**Comment by ashrambo** [comment]
Thank you, but I have errors...

https://ibb.co/qy2Jynz

**Comment by TheRobsCode** [comment]
Hey - you can comment out the Toast messages for now - they are not important.

**Comment by ashrambo** [comment]
OK sorry, I close the issue.
